export enum ROUTE_NAME {
  HOME = "home",
  PROFILE = "profile",
  TASKS = "tasks",
  TASK_DETAILS = "tasksDetails",
  RANKING = "ranking",
  BINGO = "bingo",
  SETTINGS = "settings",
  LOGIN = "login",
  REGISTER = "register",
  ADD_POINTS = "addPoints",
  KILL_GAME = "killGame",
  CONFIRM = "confirm",
  NO_ACCESS = "noAccess",
  ADMIN = "admin",
  ADMIN_LTC_QUEST = "adminLtcQuest",
  ADMIN_KILL_GAME = "adminKillGame",
  ADMIN_ADD_CARDS_KILL_GAME = "adminAddCardsKillGame",
  FAQ = "faq",
  FAQ_KILL_GAME = "faqKillGame",
}

export enum ROUTE_OPTION {
  HOME = "router.home",
  PROFILE = "router.profile",
  TASKS = "router.tasks",
  TASK_DETAILS = "router.tasksDetails",
  RANKING = "router.ranking",
  BINGO = "router.bingo",
  SETTINGS = "router.settings",
  LOGIN = "router.login",
  REGISTER = "router.register",
  ADD_POINTS = "router.addPoints",
  KILL_GAME = "router.killGame",
  CONFIRM = "router.confirm",
  NO_ACCESS = "router.noAccess",
  ADMIN = "router.admin",
  ADMIN_KILL_GAME = "router.adminKillGame",
  ADMIN_ADD_CARDS_KILL_GAME = "router.adminAddCardsKillGame",
  FAQ = "router.faq",
  FAQ_KILL_GAME = "router.faqKillGame",
}

export enum ROUTE_PATH {
  HOME = "/",
  PROFILE = "/profile",
  TASKS = "/tasks",
  TASK_DETAILS = "/tasks/:id",
  RANKING = "/ranking",
  BINGO = "/bingo",
  SETTINGS = "/settings",
  LOGIN = "/login",
  REGISTER = "/register",
  ADD_POINTS = "/addPoints",
  KILL_GAME = "/killGame",
  CONFIRM = "/confirm",
  NO_ACCESS = "/noAccess",
  ADMIN = "/admin",
  ADMIN_LTC_QUEST = "/admin/ltcQuest",
  ADMIN_KILL_GAME = "/admin/killGame",
  ADMIN_ADD_CARDS_KILL_GAME = "/admin/killGame/addCards",
  FAQ = "/faq",
  FAQ_KILL_GAME = "/faq/killGame",
}